---
title: "NSF S-STEM Project"
description: |
  *How do abiotic factors influence bacterial community assembly?*
author:
  - name: Josh Leon
    affiliation: National Science Foundation
date: "November 12, 2023"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# **Abstract**  

The burning of fossil fuels has caused the Earth’s temperature to rise by roughly 1 degree Celsius compared to pre-industrial temperatures (IPCC, 2018; Lindsey & Dahlman, 2023). Consequently, droughts in the Southwestern United States are expected to increase in intensity and length (Cook et al., 2015). These disturbances will likely favor invasive plant species over native plant species (Turbelin & Catford, 2021). The goal of this research is to improve our understanding of the response patterns exhibited by plant communities and their associated microbes under projected climate change conditions to prepare and formulate strategies that effectively bolster the resilience of the ecosystem. In 2021, we conducted stress trials on plants collected in the field to determine the abiotic factors that significantly affect plant health. The following year we once again collected plant and soil samples in the field but with the goal of characterizing the bacterial community associated with different parts of the plants. We extracted and sequenced the DNA and performed a variety of analyses in Rstudio to characterize the bacterial community. Our next steps are to inoculate another round of plants in stress trials with bacterial species associated with plants that survived the original stress trials to determine if they are a significant part of plant survival under project climate change stressors.

# **Presentations**  





